version: '3.7'
services:
  mysql:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passdocker
      - POSTGRES_DB=app
    ports:
      - '5432:5432'
  node-app:
    build: gate-simulator
    image: node-app:22.0
    ports:
      - '9999:9999'

